### PR TITLE
Added recurse switch

### PR DESCRIPTION
**Pull request by Elkhunder**
Allows for a deeper file structure while still pulling all the ps1 files correctly

### CODE REVIEW

**Comment by belibug** [comment]
Thanks for the pull request!

While we don't have hard rules on how to organize public/private folders, most projects I've seen keep it simple and avoid subfolders. It was already a bit of a struggle to get folks to use src/public and src/private, and many preferred just keeping everything in one place.

If you can point me to a couple of projects that use subfolders for PS1 files, I'm happy to approve this. Let me know what you think!

**Comment by Elkhunder** [comment]
I'm not entirely sure what the 'standard' is, but adding this feature won't affect current functionality. It would just give users the option to use subfolders if they choose. My project does deviate from the usual practice of keeping modules very specific, so it might be more of an edge case. I don't plan to seek out projects that use a subfolder structure—it's more of a personal preference. Since it's easy for me to add the switch once the module is installed, I totally understand if you prefer not to include it in the official release. It's not a big deal either way.

**Comment by belibug** [comment]
Thank you for understanding. `Recurse` is a little tricky, although its within in scope of public/private folder, its still good idea to limit to specific folder at root level to keep things under control.

I will keep this in my own tracker and if i come across any project then I include in the module. Thanks again.

**Comment by Elkhunder** [comment]
I did close it also because I found a few issues that needed to be resolved.  The recurse switch needs to be added in a few additional areas that I missed which caused some problems.  

- Needs to be added here so that the manifest has the correct functions names added to the 'FunctionsToExport' collection.  In the Build-Manifest function on line 7
$PubFunctionFiles = Get-ChildItem -Recurse -Path $data.PublicDir -Filter *.ps1

- Needs to be added here so that all the private functions are grabbed properly.  In the Build-Module function on line 15
$files = Get-ChildItem -Recurse -Path $data.PrivateDir -Filter *.ps1 -ErrorAction SilentlyContinue

**Pull request closed without merging**
